name:                redshift-cli
version:             0.1.0.0
github:              "chrismaher/redshift-cli"
license:             MIT
author:              "Chris Maher"
maintainer:          "chrismaher37@gmail.com"
copyright:           "2019 Chris Maher"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- bytestring
- text
- directory
- filepath
- mtl
- parsec
- split
- yaml
- postgresql-libpq >= 0.9
- postgresql-simple >= 0.6
- optparse-applicative >= 0.14

library:
  source-dirs: src

executables:
  redshift-cli-exe:
    main:                main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - redshift-cli

tests:
  redshift-cli-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - redshift-cli
